site_name: Yaossg's Doc
site_url: https://yaossg.com/doc/
repo_url: https://github.com/Yaossg/doc
edit_uri: ''
site_author: Yaossg
use_directory_urls: false

theme:
    name: readthedocs
    
plugins:
    - search
    - mermaid2
    

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True

nav:
    - "Yaossg's Doc": 'index.md'
    - 'Cripple C':
        - 'Cripple C': 'cripplec/README.md'
        - 基本概念: 'cripplec/concept.md'
        - 符号: 'cripplec/token.md'
        - 文本: 'cripplec/text.md'
        - 预处理器: 'cripplec/preprocessor.md'
        - 运算符（上）: 'cripplec/op-1.md'
        - 运算符（下）: 'cripplec/op-2.md'
        - 整数: 'cripplec/int.md'
        - 隐式转换: 'cripplec/conv.md'
        - cdecl: 'cripplec/cdecl.md'
    - '字符集与编码':
        - '概述': ce/overview.md
        - 'pre-Unicode':
            - 'ASCII': ce/ascii/ascii.md
