site_name: Yaossg's Doc
site_url: https://yaossg.com/doc/
repo_url: https://github.com/Yaossg/doc
site_author: Yaossg
use_directory_urls: false

theme:
    name: readthedocs

nav:
    - "Yaossg's Doc": 'index.md'
    - 'Cripple C':
        - 'Cripple C': 'cripplec/README.md'
        - 符号: 'cripplec/token.md'
        - 文本: 'cripplec/text.md'
        - 运算符（上）: 'cripplec/op-1.md'
        - 运算符（下）: 'cripplec/op-2.md'
        - 整数: 'cripplec/int.md'
        - 隐式转换: 'cripplec/conv.md'
